services:
  - type: web
    name: wa-broadcast-bot
    runtime: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: wa-broadcast-bot
          property: host
    # Render free tier ke liye important settings
    autoDeploy: true
